POST http://localhost:8081/api/v1/account
Content-Type: application/json

{
  "accountNumber": "6004485679",
  "iban": "DTBKENLI784485674",
  "bicSwift": "SWIFTKEN121234",
  "customerId": 56
}
###
GET http://localhost:8081/api/v1/account/6004485679
Accept: application/json

###
GET http://localhost:8081/api/v1/account/account-id/102
Accept: application/json

###