POST http://localhost:8082/api/v1/cards
Content-Type: application/json

{
  "cardNumber": "2244-2345-0780-1234",
  "cardType": "PRE-PAID",
  "cvv": "067",
  "pan": "23455",
  "aliasName": "JOHN DOE",
  "accountID": 1
}

###
GET http://localhost:8082/api/v1/cards/302
Content-Type: application/json
###